# Generated by Django 5.1.6 on 2025-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="audio",
            field=models.FileField(upload_to="audios/"),
        ),
    ]
